apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
  - arturoqu525.canadacentral.cloudapp.azure.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io