apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-tracker-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - arturoqu525.canadacentral.cloudapp.azure.com
    secretName: aks-ingress-tls
  rules:
  - host: arturoqu525.canadacentral.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-tracker-ui
            port: 
              number: 8080
