apiVersion: networking.k8s.io/v3
kind: Ingress
metadata:
  name: service-tracker-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - arturoqu525.canadacentral.cloudapp.azure.com
    secretName: aks-ingress-tls
  rules:
  - host: arturoqu525.canadacentral.cloudapp.azure.com
    http:
      paths:
      - path: /
        backend:
          serviceName: service-tracker-ui
          servicePort: 8080
